### ISSUE TITLE
Mod always reports there is an update available

### ISSUE THREAD

**Issue by calloatti** [gr8pefish/OpenGlider#11]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:

Mod always reports there is an update available

#### What you expected to happen:

Mod should not report that there is update available were there are none.

#### Steps to reproduce (important):

1. Load OpenGlider-1.10.2-0.2.3 in MC 1.10.2
2. Run MC
3. Click Mods Button
____
#### Affected Versions (Do *not* use "latest"):

- OpenGlider: OpenGlider-1.10.2-0.2.3
- Minecraft: 1.10.2
- Forge: 12.18.3.2281

![image](https://cloud.githubusercontent.com/assets/12817862/25314705/43f40ee8-281f-11e7-9e89-43a8b5b70d73.png)

**Comment by gr8pefish** [comment]
Thanks for the bug report.

I'll fix this when I can; it should be a quick fix, but I'm just busy right now so it won't be immediate.

**Comment by gr8pefish** [comment]
Should be fixed in later versions now. Sorry for the delay and annoyance.
