### ISSUE TITLE
[Suggestion] Glider repair cost should not require leather

### ISSUE THREAD

**Issue by WesCook** [gr8pefish/OpenGlider#12]
As copied from Curse comments:

I like the idea of requiring repair for the glider over time, but I'm just iffy on the idea of the costs raising each time you use an anvil.

Vanilla balances this with the Elytra by letting you apply the mending enchant. Currently this doesn't work for the Glider. (Sidenote: The enchant *can* actually be applied, but it has no effect).

The counter-argument I suppose is that raising anvil costs is the vanilla way, and it adds balance. However I'd argue that many mods have adopted the anvil for other purposes, so it wouldn't be that out of place.

As for balance, leather is still needed either way, it's just a different amount. At the point in time that you'd be making your second pair, it's unlikely to have any real impact on balance.

However, the reason I'd prefer it be a non-raising cost is because I don't want to be afraid to repair my glider when it's not low on durability. It becomes a problem of needing to wait to get the most use out of your limited repairs, which I find to be more frustrating than interesting from a game design perspective.

So if possible, I'd suggest removing the anvil costs increasing on repair. I think it would be a beneficial change.

**Comment by gr8pefish** [comment]
I looked into it today, and it'd be a pain internally to rewrite anvil stuff like that.

To solve this, I am going to up the base durability a lot (probably double). Also, I confirmed you can apply unbreaking/mending to the gliders as well via enchanted books in anvils.

**Comment by WesCook** [comment]
No problem, that sounds like a reasonable approach.  Thanks for looking into it.
