### ISSUE TITLE
Open gliders, 1.12. Glider in literally every category.

### ISSUE THREAD

**Issue by ghost** [gr8pefish/OpenGlider#16]
#### Issue Description:
Glider is found in every category, even in the "Delete item" slot.
http://prntscr.com/fzbr2c
http://prntscr.com/fzbrqr
http://prntscr.com/fzbrta
http://prntscr.com/fzbrva
http://prntscr.com/fzbryw

#### Steps to reproduce (important):

1. Go into a creative mode game with the mod installed.
2. Open the creative inventory.
3. Chose a category.
4. Scroll until you find the hang glider items.
5. Repeat for all other categories.
...

____
#### Affected Versions (Do *not* use "latest". Forge version is nice, but not usually necessary.):

- OpenGlider: 1.0.0
- Minecraft: 1.12
- Forge: 1.12-14.21.1.2420

**Comment by gr8pefish** [comment]
Update the mod and it will be fixed

Fixed in [this](https://github.com/gr8pefish/OpenGlider/commit/b6b0c616ac308b76d1462b582536a3c126dd15c9) commit
